### PR TITLE
Bug fix and code refactoring for document navigation

### PR DESCRIPTION
**Pull request by amoshydra**
Address:
#266 #263

### CODE REVIEW

**Review by chuajiaxuan — APPROVED** [review]
Looks good! Just that Pages.vue, Slides.vue have to check why my code isn't reflected here! :)

**Review by tharain — APPROVED** [review]
looks good to me :1st_place_medal:

**Comment by amoshydra** [comment]
@chuajiaxuan indeed your codes will get overwritten.
See: https://github.com/nus-mtp/sashimi-note/tree/dev/merge-amoshydra-pr-to-v0.1.4

We will have to manually copy over our codes before I merge `dev/document-navigation-refactor-and-fixes` into v0.1.4

**Comment by amoshydra** [comment]
@chuajiaxuan 
Reopening this pull-request, because it looks like https://github.com/nus-mtp/sashimi-note/pull/279 (your previous PR) doesn't contain any code change to `Pages.vue` and `Slides.vue`.

**Pull request merged**
